TRAIN_DATASET_PATH = r"..\\train_dataset"
TEST_DATASET_PATH = r"..\\test_dataset"

FRAME_SIZE = 4096
FRAME_OVERLAP = 2048

PRETRAIN_EPOCHS = None
EPOCHS = 40
STEPES_PER_EPOCH = 10_000
BATCH_SIZE = 64

MAX_SAMPLE_FREQUENCY = 256_000

frame_shift = FRAME_SIZE - FRAME_OVERLAP