TRAIN_DATASET_PATH = r"..\\train_dataset"
TEST_DATASET_PATH = r"..\\test_dataset"

DATA_PATH = r"..\\data"
VAL_SPLIT = 0.1

FRAME_SIZE = 4096
FRAME_OVERLAP = 2048

PRETRAIN_EPOCHS = None
EPOCHS = 50
STEPES_PER_EPOCH = 10_000
BATCH_SIZE = 64

MAX_SAMPLE_FREQUENCY = 256_000

MAXIMUM_NUMBER_OF_NOISE_CHANNELS = 8
NOISE_APLITUDE_MAX = 4
NOISE_FREQ_MAX = 48_000

frame_shift = FRAME_SIZE - FRAME_OVERLAP